### ISSUE TITLE
Release strategy for junit.contrib modules

### ISSUE THREAD

**Issue by pholser** [junit-team/junit.contrib#16]
For junit-theories, I currently have snapshots deploying to Sonatype's OSS repo. Ultimately, I'd like to release there too.

It seems like it makes sense not to build/version/release junit.contrib as a single entity, but as separate things. Should we split the submodules into separate Git repos, aggregating them under junit.contrib via [Git subtrees](http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/)?

Discuss!

**Comment by dsaff** [comment]
This would be my first foray into git subtrees.  I guess one question to consider is should we decouple even farther, and devolve junit.contrib into a set of pointers to other jars/repos hosted elsewhere on github.  Quite open to suggestions here.

**Comment by pholser** [comment]
@dsaff Agreed. If I'm understanding Git subtrees correctly, they would allow junit.contrib to consist of what amount to links to other repos, but they appear as though they are subdirectories of junit.contrib.

The advantage I see of keeping junit.contrib as a repo is that it can be a one-stop shop for "sanctioned" JUnit extensions. It affords individual module developers the ability to commit/release as desired from their repos, while allowing committers of junit.contrib to "bless" those changes and include them in junit.contrib. On the other hand, maybe there's no need for such sanction -- maybe individual modules can evolve/release as they see fit on their own, without oversight from committers of junit.contrib.

I feel that theories was kind of a special case, in that it derived from material in JUnit core. When we discussed solutions to https://github.com/junit-team/junit/issues/64, we thought maybe moving theories over to junit.contrib and evolving the necessary changes there would be the best course of action. So far, so good -- but maybe it makes sense to have it be a project unto its own, whether junit.contrib gets involved or not.

Whichever way to go with theories and the other "modules" of junit.contrib -- whether to keep them as part of junit.contrib, split them into separate repos and subtree-link those repos into junit.contrib, or disband junit.contrib and let the modules live/build/release in their own GitHub repos, I'm OK. I would like to get junit-theories ultimately released so that junit-quickcheck can proceed, so from a selfish standpoint, whatever works best to accomplish that I'd go for. I thought I'd bring it up here in case other module contributors/developers have opinions also.

**Comment by dsaff** [comment]
I'm convinced of the subtree option.  Let me know what I can do to make it so.

**Comment by pholser** [comment]
I think this is what's required to get started:

0) junit-team blows away the 'theories' subdirectory from junit-team/junit.contrib and commits the change.

1) I will create a new repo for the new theories implementation: git@github.com:pholser/junit-theories.git

2) junit-team brings in the new repo as a subtree of junit.contrib and commits it:

```
$ git subtree add --prefix=theories git://github.com/pholser/junit-theories.git master
```

3) When desired, junit-team can pull in changes from the remote repo via:

```
$ git subtree pull --prefix=theories git://github.com/pholser/junit-theories.git master
$ git push
```

I'll set about doing 1) this evening.

**Comment by pholser** [comment]
If you don't have git-subtree installed, you can get it here: https://github.com/apenwarr/git-subtree

**Comment by pholser** [comment]
@dsaff I've created a new repo for junit-theories (item 1 in list above). When ready, please bring this repo in as a subtree of junit.contrib called 'theories'.

**Comment by pholser** [comment]
@dsaff Let me know when you've got 0) and 2) above done. At that point, I'll declare junit-theories as 4.11, release to Maven central, etc., then set about getting it current with the 4.12 work. :)

**Comment by dsaff** [comment]
Paul,

Sounds good.  Sorry for the delay.

**Comment by dsaff** [comment]
OK, I think that I've got (0) and (2) done correctly.  Please correct me if
needed.  :-)

**Comment by pholser** [comment]
@dsaff This looks correct. Closing. Thanks so much! Releases of theories 4.11 and junit-quickcheck will be forthcoming soon.
