### ISSUE TITLE
Bring junit-theories 4.12 into contrib

### ISSUE THREAD

**Issue by pholser** [junit-team/junit.contrib#20]
I have a new release of the [junit-theories machinery](https://github.com/pholser/junit-theories), that incorporates the changes made in JUnit 4.12, while retaining the extras of supporting generics on theory parameter types, as described [here](https://github.com/junit-team/junit/issues/64). I'd like to fold these changes into junit.contrib's subtree, as we did with the previous 4.11 release. It should involve performing the following commands:

```
$ git subtree pull --prefix=theories git://github.com/pholser/junit-theories.git master
$ git push
```

More on "git subtree" [here](http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/).

Thanks!

**Comment by pholser** [comment]
Hi @junit-team, any thoughts on this one?

**Comment by dsaff** [comment]
Now that 4.12 is out, makes sense to me.  Others?

**Comment by marcphilipp** [comment]
Me too. I'm wondering however... what stands in the way of @pholser doing it himself? Only access rights? Do we do any kind of "quality checking"?

**Comment by pholser** [comment]
Not sure whether this qualifies as access rights problem:

```
prholser@prholser:junit.contrib (master)$ git subtree pull --prefix=theories git://github.com/pholser/junit-theories.git master
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=Connection refused
```

I can connect to GitHub in usual ways otherwise.

**Comment by dsaff** [comment]
I can't imagine that particular failure having anything to do with rights on the junit-team fork, since that should be your own fork.

Unfortunately, I can never remember the dancing I do whenever I set up a new connection to github to make such things work, so your perusal of the relevant docs is likely as effective as mine, I'm sorry to say.

**Comment by pholser** [comment]
Pull req above should do the trick.

**Comment by pholser** [comment]
Subtree merged.
